defmodule AdventOfCode2024.Day08Test do
  use ExUnit.Case, async: true

  alias AdventOfCode2024.Day08

  test "Day08 part A example" do
    assert Day08.part_a(example_input()) == 14
  end

  defp example_input() do
    """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
    |> String.trim()
    |> String.split("\n")
    |> Enum.map(&String.trim/1)
  end

  @tag :skip
  test "Day08 part B example" do
    assert Day08.part_b(example_input()) == :something_else
  end
end
